import type { MantineThemeOverride, CSSVariablesResolver } from '@mantine/core';
import { colors } from './colors';
import { typography } from './typography';

export const theme: MantineThemeOverride = {
  primaryColor: 'blue',
  spacing: {
    xs: '4px',
    sm: '8px',
    md: '12px',
    lg: '20px',
    xl: '24px',
  },
  radius: {
    xs: '4px',
    sm: '8px',
    md: '12px',
    lg: '20px',
    xl: '24px',
  },
  breakpoints: {
    xs: '36em',
    sm: '48em',
    md: '62em',
    lg: '75em',
    xl: '88em',
  },
  other: {
    colors,
    typography,
  },
};

export const cssVariablesResolver: CSSVariablesResolver = () => ({
  variables: {},
  light: {
    '--color-base-surface-primary': colors.base.surface.primary,
    '--color-base-surface-secondary': colors.base.surface.secondary,
    '--color-base-surface-tertiary': colors.base.surface.tertiary,
    '--color-base-surface-quaternary': colors.base.surface.quaternary,
    '--color-base-content-top': colors.base.content.top,
    '--color-base-content-primary': colors.base.content.primary,
    '--color-base-content-secondary': colors.base.content.secondary,
    '--color-base-content-tertiary': colors.base.content.tertiary,
    '--color-base-content-quaternary': colors.base.content.quaternary,
    '--color-base-content-quintarny': colors.base.content.quintarny,
    '--color-base-action-primary-default': colors.base.action.primary.default,
    '--color-base-action-primary-hover': colors.base.action.primary.hover,
    '--color-base-action-primary-active': colors.base.action.primary.active,
    '--color-base-action-primary-disable': colors.base.action.primary.disable,
    '--color-base-action-primary-bg': colors.base.action.primary.bg,
    '--color-base-action-primary-bg10': colors.base.action.primary.bg10,
    '--color-base-action-secondary-default': colors.base.action.secondary.default,
    '--color-base-action-secondary-hover': colors.base.action.secondary.hover,
    '--color-base-action-secondary-active': colors.base.action.secondary.active,
    '--color-base-action-secondary-disable': colors.base.action.secondary.disable,
    '--color-base-action-secondary-bg': colors.base.action.secondary.bg,
    '--color-base-action-secondary-bg10': colors.base.action.secondary.bg10,
    '--color-base-action-destructive-default': colors.base.action.destructive.default,
    '--color-base-action-destructive-hover': colors.base.action.destructive.hover,
    '--color-base-action-destructive-active': colors.base.action.destructive.active,
    '--color-base-action-destructive-disable': colors.base.action.destructive.disable,
    '--color-base-action-destructive-bg': colors.base.action.destructive.bg,
    '--color-base-action-destructive-bg10': colors.base.action.destructive.bg10,
    '--color-base-state-success-fg': colors.base.state.success.fg,
    '--color-base-state-success-bg': colors.base.state.success.bg,
    '--color-base-state-warning-fg': colors.base.state.warning.fg,
    '--color-base-state-warning-bg': colors.base.state.warning.bg,
    '--color-base-state-error-fg': colors.base.state.error.fg,
    '--color-base-state-error-bg': colors.base.state.error.bg,
    '--color-base-state-info-fg': colors.base.state.info.fg,
    '--color-base-state-info-bg': colors.base.state.info.bg,
    '--color-base-state-help-fg': colors.base.state.help.fg,
    '--color-base-state-help-bg': colors.base.state.help.bg,
    '--color-base-ascent-1-fg': colors.base.ascent[1].fg,
    '--color-base-ascent-1-bg': colors.base.ascent[1].bg,
    '--color-base-ascent-2-fg': colors.base.ascent[2].fg,
    '--color-base-ascent-2-bg': colors.base.ascent[2].bg,
    '--color-base-ascent-3-fg': colors.base.ascent[3].fg,
    '--color-base-ascent-3-bg': colors.base.ascent[3].bg,
    '--color-base-ascent-4-fg': colors.base.ascent[4].fg,
    '--color-base-ascent-4-bg': colors.base.ascent[4].bg,
    '--color-base-ascent-5-fg': colors.base.ascent[5].fg,
    '--color-base-ascent-5-bg': colors.base.ascent[5].bg,
  },
  dark: {
    '--color-base-surface-primary': colors.inverse.surface.primary,
    '--color-base-surface-secondary': colors.inverse.surface.secondary,
    '--color-base-surface-tertiary': colors.inverse.surface.tertiary,
    '--color-base-surface-quaternary': colors.inverse.surface.quaternary,
    '--color-base-content-top': colors.inverse.content.top,
    '--color-base-content-primary': colors.inverse.content.primary,
    '--color-base-content-secondary': colors.inverse.content.secondary,
    '--color-base-content-tertiary': colors.inverse.content.tertiary,
    '--color-base-content-quaternary': colors.inverse.content.quaternary,
    '--color-base-content-quintarny': colors.inverse.content.quintarny,
    '--color-base-action-primary-default': colors.inverse.action.primary.default,
    '--color-base-action-primary-hover': colors.inverse.action.primary.hover,
    '--color-base-action-primary-active': colors.inverse.action.primary.active,
    '--color-base-action-primary-disable': colors.inverse.action.primary.disable,
    '--color-base-action-primary-bg': colors.inverse.action.primary.bg,
    '--color-base-action-primary-bg10': colors.inverse.action.primary.bg10,
    '--color-base-action-secondary-default': colors.inverse.action.secondary.default,
    '--color-base-action-secondary-hover': colors.inverse.action.secondary.hover,
    '--color-base-action-secondary-active': colors.inverse.action.secondary.active,
    '--color-base-action-secondary-disable': colors.inverse.action.secondary.disable,
    '--color-base-action-secondary-bg': colors.inverse.action.secondary.bg,
    '--color-base-action-secondary-bg10': colors.inverse.action.secondary.bg10,
    '--color-base-action-destructive-default': colors.inverse.action.destructive.default,
    '--color-base-action-destructive-hover': colors.inverse.action.destructive.hover,
    '--color-base-action-destructive-active': colors.inverse.action.destructive.active,
    '--color-base-action-destructive-disable': colors.inverse.action.destructive.disable,
    '--color-base-action-destructive-bg': colors.inverse.action.destructive.bg,
    '--color-base-action-destructive-bg10': colors.inverse.action.destructive.bg10,
    '--color-base-state-success-fg': colors.inverse.state.success.fg,
    '--color-base-state-success-bg': colors.inverse.state.success.bg,
    '--color-base-state-warning-fg': colors.inverse.state.warning.fg,
    '--color-base-state-warning-bg': colors.inverse.state.warning.bg,
    '--color-base-state-error-fg': colors.inverse.state.error.fg,
    '--color-base-state-error-bg': colors.inverse.state.error.bg,
    '--color-base-state-info-fg': colors.inverse.state.info.fg,
    '--color-base-state-info-bg': colors.inverse.state.info.bg,
    '--color-base-state-help-fg': colors.inverse.state.help.fg,
    '--color-base-state-help-bg': colors.inverse.state.help.bg,
    '--color-base-ascent-1-fg': colors.inverse.ascent[1].fg,
    '--color-base-ascent-1-bg': colors.inverse.ascent[1].bg,
    '--color-base-ascent-2-fg': colors.inverse.ascent[2].fg,
    '--color-base-ascent-2-bg': colors.inverse.ascent[2].bg,
    '--color-base-ascent-3-fg': colors.inverse.ascent[3].fg,
    '--color-base-ascent-3-bg': colors.inverse.ascent[3].bg,
    '--color-base-ascent-4-fg': colors.inverse.ascent[4].fg,
    '--color-base-ascent-4-bg': colors.inverse.ascent[4].bg,
    '--color-base-ascent-5-fg': colors.inverse.ascent[5].fg,
    '--color-base-ascent-5-bg': colors.inverse.ascent[5].bg,
  },
});
